apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: core-queueing-library
  description: Push jobs onto a globally available shared queue.
spec:
  type: library
  lifecycle: production
  owner: roadie
  dependencyOf:
    - Component:passenger-backend
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: core-auth-module
  description: Authenticate incoming requests.
spec:
  type: library
  lifecycle: production
  owner: roadie
